### PR TITLE
Remove controller

### PR DESCRIPTION
**Pull request by lennym**
The controller is now in the hof-controllers project, and is loaded from there as a dependency

### CODE REVIEW

**Comment by JoeChapman** [comment]
@lennym CONFLICTS!

**Comment by lennym** [comment]
Yeah... I decided to merge @joefitter's ES6ify PR because I hate myself and enjoy suffering.

**Comment by lennym** [comment]
UNCONFLICTS!

**Comment by lennym** [comment]
Now with added changelog because I'd like to publish ASAP

**Review by joefitter — APPROVED** [review]
DELETE ALL THE CODEZ

**Comment by joefitter** [comment]
(or just move it elsewhere)

**Review by JoeChapman — APPROVED** [review]

**Pull request merged**
