### PR TITLE
Devtask - ES6ify

### PR DESCRIPTION
**Pull request by joefitter**
* updated to use es6 code
* installed eslint-config-homeoffice
* fixed code in line with linter
* use hof-model

### CODE REVIEW

**Comment by joefitter** [comment]
@JoeChapman @easternbloc @danielepolencic - mind having a look when you get a sec please?

**Comment by JoeChapman** [comment]
@joefitter @lennym  is this still relevant considering our conversation this afternoon about restructuring the controllers?

**Comment by joefitter** [comment]
why wouldn't it be? all this is doing is refactoring to es6, which we would need to do if we moved the controller to hof-controllers anyway

**Comment by lennym** [comment]
Is this PR good to merge? If it is then it would be good to merge before the restructure so the work's not lost. 

I'm assuming that's what @joefitter was getting at.

**Comment by lennym** [comment]
Tests are failing for me locally. Not sure why this hasn't been travis-ed.

**Comment by joefitter** [comment]
@lennym looking now, its pretty old so not surprised its failing

**Comment by lennym** [comment]
It's failing outside the controllers, so I'll copy the ES6 controller code into hof-form-controllers (because eslint in that project freaks *out* if I copy the master code).

**Comment by joefitter** [comment]
sounds good, I'll fix this branch and then PR the removal of the controllers

**Comment by joefitter** [comment]
@lennym looks like travis was turned off for a few repos, including hof-form-controller. I have enabled it now

**Comment by joefitter** [comment]
@JoeChapman @easternbloc @lennym passing now, mind giving this a 👍

**Pull request merged**
